name: CI/CD Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: Passimx/ci-cd-workflows/.github/workflows/version.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
      contents: write